title: English/Linguistics 2200 @ Iowa State
description: This is the repository for ENGL/LING 2200 in Spring 2025 at Iowa State University.
theme: just-the-docs

aux_links:
  Canvas Link: https://canvas.iastate.edu/courses/118016
